name: s3_deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::603675346890:role/sample2_deploy_role
          aws-region: ap-northeast-1

      - name: install dependencies
        run: npm install

      - name: build
        run: npm run build

      - name: deploy
        run: aws s3 sync ./build s3://${{secrets.S3_BUCKET_NAME}} --exact-timestamps --region ap-northeast-1
